In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import csv
import numpy as np
import time
from tqdm import tqdm_notebook as tqdm
import re
from urllib.request import Request, urlopen

## Cookbooks Genre

In [31]:
number_of_pages = list(range(1,3))
all_books = []

for number in number_of_pages:
    page = requests.get(f'https://www.goodreads.com/list/show/9619.True_Life_Adventure?page={number}')
    soup = BeautifulSoup(page.content, 'html.parser')
    table = soup.find('table', attrs={'class': 'tableList js-dataTooltip'})
    table_body = table.find_all('tr')

    for entry in table_body:
        try:
            hrefs = entry.find_all(href=True)

            #get the book title
            title = hrefs[0]['title']

            #get the book author
            author = hrefs[2].get_text()

            #get the book link
            baseurl = 'https://www.goodreads.com'
            link1 = baseurl + hrefs[0]['href']
            link = hrefs[0]['href']

            #get the description of the book through its link
            page2 = requests.get(f'https://www.goodreads.com{link}')
            soup2 = BeautifulSoup(page2.content, 'html.parser')

            #select the description box
            description_box = soup2.find_all('div', attrs={'id': 'description'})

            #get the summary of each book
            book_text = description_box[0].find_all('span')[1].get_text()

            #book pictures
            image_box = soup2.find_all('img', attrs={'id' : 'coverImage'})
            picture = image_box[0]['src']

            #number of pages
            page_box = soup2.find_all('span', attrs={'itemprop':'numberOfPages'})
            page_count = page_box[0].get_text()
            
            #number of ratings
            rate_box = soup2.find_all('span', attrs={'itemprop':'ratingValue'})
            rate_count = rate_box[0].get_text()
            
            #publications
            public_box = soup2.find_all('div', attrs={'class':'row'})
            public_count = public_box[1].get_text()

            #genres
            genre_box = soup2.find_all('a', attrs={'class':'actionLinkLite bookPageGenreLink'})
            genre_list = []
            for genre in genre_box:
                genre_list.append(genre.get_text())

            #add to dictionary
            row_profile = {'name':title, 'author':author, 'link':link1, 'text':book_text,'picture':picture,
                            'page number':page_count[0:4],'rating':rate_count,'publications':public_count,'genres':genre_list[0]}

            all_books.append(row_profile)

            print(title)
        except:
            pass
    print(f'page {number} is done!')
    
f = open("books_humor2.csv", "w",encoding="utf-8")
writer = csv.DictWriter(f, fieldnames=['name', 'author', 'link', 'text', 'picture',
                                       'page number', 'rating','publications', 'genres'])
writer.writeheader()
writer.writerows(all_books)
f.close()

Into Thin Air: A Personal Account of the Mount Everest Disaster
Into the Wild
Alive: The Story of the Andes Survivors
The Perfect Storm: A True Story of Men Against the Sea
In the Heart of the Sea: The Tragedy of the Whaleship Essex
Kon-Tiki
Miracle in the Andes
Skeletons on the Zahara: A True Story of Survival
The Places in Between
Promise of Departure
127 Hours: Between a Rock and a Hard Place
The Endurance: Shackleton's Legendary Antarctic Expedition
The Right Stuff
Wild: From Lost to Found on the Pacific Crest Trail
Out of Africa
Signs of Life: To the Ends of the Earth with a Doctor
Kokoda Trek: 75th Anniversary
AfterTastes and Tales from Russia
The Worst Journey in the World
Over the Edge of the World: Magellan's Terrifying Circumnavigation of the Globe
Adrift: Seventy-Six Days Lost at Sea
The Riddle of the Labyrinth: The Quest to Crack an Ancient Code
The Bounty: The True Story of the Mutiny on the Bounty
On the Road
Down the Great Unknown: John Wesley Powell's 1869 Journey of Discovery and Tragedy Through the Grand Canyon
A Woman in Berlin: Eight Weeks in the Conquered City: A Diary
Into Africa: The Epic Adventures of Stanley & Livingstone
Chance Encounters: Travel Tales from Around the World
The Extraordinary Voyage of Pytheas the Greek
Undaunted Courage: The Pioneering First Mission to Explore America's Wild Frontier
Dark Waters
The Last Place on Earth: Scott and Amundsen's Race to the South Pole
Sea of Glory: America's Voyage of Discovery, the U.S. Exploring Expedition, 1838-1842
As Far as My Feet Will Carry Me: The Extraordinary True Story of One Man's Escape from a Siberian Labour Camp and His 3-Year Trek to Freedom
Krakatoa: The Day the World Exploded: August 27, 1883
Papillon
Rabbit-Proof Fence: The True Story of One of the Greatest Escapes of All Time
Wild: An Elemental Journey
Blind Descent
Waiting for the Dalai Lama: Stories from All Sides of the Tibetan Debate
Paradise Creek: A True Story of Adventure in the Canadian Wilderness
Uttermost Part of the Earth
The Captured
Fatu-Hiva: Back to Nature
Trespassers on the Roof of the World: The Secret Exploration of Tibet
Sailing Alone around the World
Farthest North
30,000 Leagues Undersea: True Tales of a Submariner and Deep Submergence Pilot
The Explorer's Mindset: Unlock Health Happiness and Success the Fun Way
You Can't Drive Your Car to Your Own Funeral
The Two Week Traveller
The Next Everest: Surviving the Mountain's Deadliest Day and Finding the Resilience to Climb Again
In the Kingdom of Ice: The Grand and Terrible Polar Voyage of the USS Jeannette
Full Tilt: Ireland to India with a Bicycle
Round Ireland with a Fridge
Desert Queen: The Extraordinary Life of Gertrude Bell: Adventurer, Adviser to Kings, Ally of Lawrence of Arabia
Ladies of the Field: Early Women Archaeologists and Their Search for Adventure
Lost on Everest: The Search for Mallory and Irvine
Catfish and Mandala: A Two-Wheeled Voyage Through the Landscape and Memory of Vietnam
Dying in Indian Country: A Family Journey from Self-Destruction to Opposing Tribal Sovereignty
Ghost in the Wires: My Adventures as the World's Most Wanted Hacker
Little Ship of Fools: Sixteen Rowers, One Improbable Boat, Seven Tumultuous Weeks on the Atlantic
Between Man and Beast: An Unlikely Explorer, the Evolution Debates, and the African Adventure That Took the Victorian World by Storm
The Cruelest Miles: The Heroic Story of Dogs and Men in a Race Against an Epidemic
Quest and Crew
The Brendan Voyage: A Leather Boat Tracks the Discovery of America by the Irish Sailor Saints
And I Alone Survived
God's Smuggler
By Any Means: His Brand New Adventure from Wicklow to Wollongong
Barrow's Boys: The Original Extreme Adventurers: A Stirring Story of Daring Fortitude and Outright Lunacy
page 1 is done!
Mysterious Things in the Woods
Sky Burial: An Epic Love Story Of Tibet
Right to the Edge: Sydney to Toyko by Any Means
The Sacrament: The Incredible Story of Brent Dyer and Donna Johnson
Extreme Frontiers: Racing Across Canada from Newfoundland to the Rockies
My Life as an Explorer
Captive: My Time as a Prisoner of the Taliban
Exploring Titanic: The Expeditions of James Cameron
The Thrilling Adventures of Lovelace and Babbage
Travels with a Tangerine: A Journey in the Footnotes of Ibn Battutah
The First Frontier: The Forgotten History of Struggle, Savagery, and Endurance in Early America
The Art of Stillness: Adventures in Going Nowhere
Mad, Bad & Dangerous to Know: The Autobiography
Mawson's Will: The Greatest Polar Survival Story Ever Written
Ordeal by Hunger: The Story of the Donner Party
In Patagonia
Mountains of the Mind: A History of a Fascination
The Last Grain Race
The Last Goodnight: A World War II Story of Espionage, Adventure & Betrayal
The Wilder Life: My Adventures in the Lost World of Little House on the Prairie
Dreaming of East: Western Women and the Exotic Allure of the Orient
Ordeal by Ice: The Search for the Northwest Passage
They're Rugby Boys, Don't You Know?
A Year of Living Prayerfully: How a Curious Traveler Met the Pope, Walked on Coals, Danced with Rabbis, and Revived His Prayer Life
Facing the Congo: A Modern-Day Journey into the Heart of Darkness
East in Eden
Adventures of a Railway Nomad: How Our Journeys Guide Us Home
Find Your Purpose Using Science
Cool Creatures, Hot Planet: Exploring the Seven Continents
The Spirit of Villarosa: A Father's Extraordinary Adventures; A Son's Challenge
Off Grid and Free: My Path to the Wilderness
Journals of Patrick Gass
Travel as Transformation: Conquer the Limits of Culture to Discover Your Own Identity
Peanut Butter and Passports: Driving Apes, Skivvy Skydivers And Travel Tales From Around The World
Tracks
Writer, Sailor, Soldier, Spy: Ernest Hemingway's Secret Adventures, 1935-1961
Hacia los confines del mundo
Strangers in the Storm: Love and Survival on Mount Rainier
A Maverick Himalayan Way (new edition): Discover the Himalayas and the Indian Subcontinent with Kiwi Adventurer Mary Jane Walker!
The Hitchhiker Man
Lies We Tell Mothers
Views from the Cockpit: The Journey of a Son
The Ledge: An Adventure Story of Friendship and Survival on Mount Rainier
Through Sand & Snow: a man, a bicycle, and a 43,000-mile journey to adulthood via the ends of the Earth
Friends: Voices on the Gift of Companionship
Red Earth Diaries: A Migrant Couple's Backpacking Adventure in Australia
The Camino de Santiago: One Wanderful Walk
Nanga Parbat Pilgrimage: The Lonely Challenge
Barbed Wire and Babushkas: A river odyssey across siberia
Quest for the Virgins
A Time of Gifts
Endangered Edens: Exploring the Arctic National Wildlife Refuge, Costa Rica, the Everglades, and Puerto Rico
The Devil Wears Clogs
Race to the South Pole
page 2 is done!

In [32]:
data = pd.read_csv("books_humor2.csv",)
data

,name,author,link,text,picture,page number,rating,publications,genres
0,Into Thin Air: A Personal Account of the Mount...,Jon Krakauer,https://www.goodreads.com/book/show/1898.Into_...,A bank of clouds was assembling on the not-so-...,https://i.gr-assets.com/images/S/compressed.ph...,368,4.19,\r\n Published\r\n October 1...,Nonfiction
1,Into the Wild,Jon Krakauer,https://www.goodreads.com/book/show/1845.Into_...,Librarian's Note: An alternate cover edition c...,https://i.gr-assets.com/images/S/compressed.ph...,207,3.99,\r\n Published\r\n January 2...,Nonfiction
2,Alive: The Story of the Andes Survivors,Piers Paul Read,https://www.goodreads.com/book/show/401514.Alive,"On October 12, 1972, a plane carrying a team o...",https://i.gr-assets.com/images/S/compressed.ph...,318,4.08,\r\n Published\r\n December ...,Nonfiction
3,The Perfect Storm: A True Story of Men Against...,Sebastian Junger,https://www.goodreads.com/book/show/108229.The...,"""Takes readers into the maelstrom and shows na...",https://i.gr-assets.com/images/S/compressed.ph...,227,4.09,\r\n Published\r\n January 1...,Nonfiction
4,In the Heart of the Sea: The Tragedy of the Wh...,Nathaniel Philbrick,https://www.goodreads.com/book/show/17780.In_t...,"""With its huge, scarred head halfway out of th...",https://i.gr-assets.com/images/S/compressed.ph...,302,4.10,\r\n Published\r\n May 1st 2...,History
...,...,...,...,...,...,...,...,...,...
119,Quest for the Virgins,David Beaupre,https://www.goodreads.com/book/show/25381716-q...,Beginning with the crossing of the feared Mona...,https://i.gr-assets.com/images/S/compressed.ph...,250,4.18,\r\n Published\r\n April 16t...,Adventure
120,A Time of Gifts,Patrick Leigh Fermor,https://www.goodreads.com/book/show/253984.A_T...,"In 1933, at the age of 18, Patrick Leigh Fermo...",https://i.gr-assets.com/images/S/compressed.ph...,321,4.06,\r\n Published\r\n October 3...,Travel
121,Endangered Edens: Exploring the Arctic Nationa...,Marty Essen,https://www.goodreads.com/book/show/26195794-e...,\r\nEndangered Edens\r\n is the long-awaited f...,https://i.gr-assets.com/images/S/compressed.ph...,152,4.21,\r\n Published\r\n January 8...,Travel
122,The Devil Wears Clogs,Jennifer Burge,https://www.goodreads.com/book/show/24707412-t...,Have you contemplated what your life would hav...,https://i.gr-assets.com/images/S/compressed.ph...,245,3.66,\r\n Published\r\n January 2...,Travel
123,Race to the South Pole,Roald Amundsen,https://www.goodreads.com/book/show/397060.Rac...,"Part historical essay, part scientific article...",https://i.gr-assets.com/images/S/compressed.ph...,256,4.19,\r\n Published\r\n March 13t...,Nonfiction

In [33]:
genre_list

['Nonfiction',
 'History',
 'Travel',
 'Biography',
 'Adventure',
 'Autobiography',
 'Memoir',
 'Science',
 'Historical',
 'Environment',
 'Nature',
 'Biography',
 'Autobiography']

In [34]:
data['genres'].value_counts()

Nonfiction        52
Travel            32
History           22
Adventure          4
Biography          3
Christian          2
Autobiography      1
Sequential Art     1
Historical         1
Politics           1
Sports             1
Classics           1
Fiction            1
Cultural           1
Self Help          1
Name: genres, dtype: int64

## Biography Genre

In [16]:
number_of_pages = list(range(26,28))
all_books = []

for number in number_of_pages:
    page = requests.get(f'https://www.goodreads.com/list/show/281.Best_Memoir_Biography_Autobiography?page={number}')
    soup = BeautifulSoup(page.content, 'html.parser')
    table = soup.find('table', attrs={'class': 'tableList js-dataTooltip'})
    table_body = table.find_all('tr')

    for entry in table_body:
        try:
            hrefs = entry.find_all(href=True)

            #get the book title
            title = hrefs[0]['title']

            #get the book author
            author = hrefs[2].get_text()

            #get the book link
            baseurl = 'https://www.goodreads.com'
            link1 = baseurl + hrefs[0]['href']
            link = hrefs[0]['href']

            #get the description of the book through its link
            page2 = requests.get(f'https://www.goodreads.com{link}')
            soup2 = BeautifulSoup(page2.content, 'html.parser')

            #select the description box
            description_box = soup2.find_all('div', attrs={'id': 'description'})

            #get the summary of each book
            book_text = description_box[0].find_all('span')[1].get_text()

            #book pictures
            image_box = soup2.find_all('img', attrs={'id' : 'coverImage'})
            picture = image_box[0]['src']

            #number of pages
            page_box = soup2.find_all('span', attrs={'itemprop':'numberOfPages'})
            page_count = page_box[0].get_text()
            
            #number of ratings
            rate_box = soup2.find_all('span', attrs={'itemprop':'ratingValue'})
            rate_count = rate_box[0].get_text()
            
            #publications
            public_box = soup2.find_all('div', attrs={'class':'row'})
            public_count = public_box[1].get_text()

            #genres
            genre_box = soup2.find_all('a', attrs={'class':'actionLinkLite bookPageGenreLink'})
            genre_list = []
            for genre in genre_box:
                genre_list.append(genre.get_text())

            #add to dictionary
            row_profile = {'name':title, 'author':author, 'link':link1, 'text':book_text,'picture':picture,
                            'page number':page_count,'rating':rate_count,'publications':public_count,'genres':genre_list[3]}

            all_books.append(row_profile)

            print(title)
        except:
            pass
    print(f'page {number} is done!')
    
f = open("books_biography6.csv", "w",encoding="utf-8")
writer = csv.DictWriter(f, fieldnames=['name', 'author', 'link', 'text', 'picture',
                                       'page number', 'rating','publications', 'genres'])
writer.writeheader()
writer.writerows(all_books)
f.close()

The Insurgents: David Petraeus and the Plot to Change the American Way of War
The Power of Positive Leadership: How and Why Positive Leaders Transform Teams and Organizations and Change the World
A Sand County Almanac and Sketches Here and There
The House of the Spirits
Fouché
The Angle of Flickering Light
Why Fish Don't Exist: A Story of Loss, Love, and the Hidden Order of Life
Sugar Ray
Rolling Away: My Agony with Ecstasy
Confessions of a Tax Collector: One Man's Tour of Duty Inside the IRS
Welfare Brat
When the Heart Waits: Spiritual Direction for Life's Sacred Questions
If I Get to Five: What Children Can Teach Us About Courage and Character
The Possibility of Everything
Self-Consciousness
Welcome, Silence
Stones Into Schools: Promoting Peace With Books, Not Bombs, in Afghanistan and Pakistan
After the Wall
The Sharper Your Knife, the Less You Cry: Love, Laughter, and Tears at the World's Most Famous Cooking School in Paris
Time Traveler: A Scientist's Personal Mission to Make Time Travel a Reality
The Bedwetter: Stories of Courage, Redemption, and Pee
Beatrix Potter: A Life in Nature
The Gate
Most People I Know
How to Love an American Man: A True Story
The World of Yesterday
The Day Huey Long Was Shot
I Am Jackie Chan: My Life in Action
Sin
Nice Recovery
Land of the Burnt Thigh
You Remind Me of You: A Poetry Memoir
Traplines: Coming Home to Sawtooth Valley
Thomas Jefferson: An Intimate History
The Test of Courage: Michel Thomas
The Meaning of Matthew: My Son's Murder in Laramie, and a World Transformed
Boy Racer
Joseph Anton: A Memoir
The Cap: The Price Of A Life
Another Life: A Memoir of Other People
Scarred: She was a slave to her father. Pain was her only escape.
Driving the Birds
Wellington: The Path to Victory 1769-1814
Tell My Sons: A Father's Last Letters
Socrates: The Man and His Thought
Big Man: Real Life & Tall Tales
Atatürk: The Rebirth Of A Nation
George Washington's Secret Six: The Spy Ring That Saved the American Revolution
It Happened In India: The Story of Pantaloons, Big Bazaar, Central and the Great Indian Consumer
Me
Rat Girl
Lying: A Metaphorical Memoir
I am Sophie Tucker: A Fictional Memoir
page 26 is done!
The Fifties Mystique
Trafficked
Redeeming Love
Mo' Meta Blues: The World According to Questlove
BLOW: How a Small-Town Boy Made $100 Million with the Medellín Cocaine Cartel and Lost It All
Fast N' Loud: Blood, Sweat and Beers
Bir Dinozorun Anıları
A Personal Odyssey
The First Tycoon: The Epic Life of Cornelius Vanderbilt
Wilson
American Ulysses: A Life of Ulysses S. Grant
Between Two Worlds. Escape From Tyranny : Growing Up in the Shadow of Saddam
Beethoven: Der einsame Revolutionär.
Mortality
Play On: Now, Then, And Fleetwood Mac
Stories of My Life
Returning to Earth
The Black River Chronicles: Level One
A Time of Gifts
The Secret of the Nagas
Shark Drunk: The Art of Catching a Large Shark from a Tiny Rubber Dinghy in a Big Ocean
We Die Alone: A WWII Epic of Escape and Endurance
Below Stairs
The Gulag Archipelago, 1918 - 1956: An Experiment in Literary Investigation, Books I-II
The Ascent of Money: A Financial History of the World
Nothing Like Normal: Surviving a Sibling's Schizophrenia
No God but One: Allah or Jesus?: A Former Muslim Investigates the Evidence for Islam and Christianity
Spectacles
The Death of an Heir: Adolph Coors III and the Murder That Rocked an American Brewing Dynasty
Code Name: Johnny Walker: The Extraordinary Story of the Iraqi Who Risked Everything to Fight with the U.S. Navy SEALs
Leonardo da Vinci
The Man Who Outshone The Sun King: Ambition, Triumph and Treachery in the Reign of Louis XIV
For Young Women Only: What You Need to Know about How Guys Think
Open Horizons
Assata: An Autobiography
Deep Enough for Ivorybills
The Lost City of the Monkey God: A True Story
Sick: A Memoir
War Child: A Child Soldier's Story
Serious Pleasures: the Life of Stephen Tennant
Stevie Nicks: Visions, Dreams & Rumors
With the Old Breed: At Peleliu and Okinawa
Interesting Times: A Twentieth-Century Life
West
Messenger of Beauty: The Life and Visionary Art of Nicholas Roerich
No Surrender: A Father, a Son, and an Extraordinary Act of Heroism That Continues to Live on Today
Can't Hurt Me: Master Your Mind and Defy the Odds
Memoirs of a Geisha
Tesla: Inventor of the Electrical Age
Ray By Ray: A Daughter's Take on the Legend of Nicholas Ray
Rough Magic: Riding the World's Loneliest Horse Race
The Sixth Extinction: An Unnatural History
Holocaust Memoirs by a Bergen-Belsen survivor & Classmate of Anne Frank
A Hippo Love Story
George Whitefield: God's Anointed Servant in the Great Revival of the Eighteenth Century
Flying Free: My Victory over Fear to Become the First Latina Pilot on the US Aerobatic Team
Sigh, Gone: A Misfit's Memoir of Great Books, Punk Rock, and the Fight to Fit In
The Year of Living Danishly: My Twelve Months Unearthing the Secrets of the World's Happiest Country
page 27 is done!

In [17]:
data1 = pd.read_csv("books_biography6.csv")
data1

,name,author,link,text,picture,page number,rating,publications,genres
0,The Insurgents: David Petraeus and the Plot to...,Fred Kaplan,https://www.goodreads.com/book/show/15802422-t...,The Insurgents is the inside story of the smal...,https://i.gr-assets.com/images/S/compressed.ph...,418 pages,4.06,\r\n Published\r\n January 2...,Politics
1,The Power of Positive Leadership: How and Why ...,Jon Gordon,https://www.goodreads.com/book/show/32027331-t...,We are not positive because life is easy. We a...,https://i.gr-assets.com/images/S/compressed.ph...,208 pages,4.18,\r\n Published\r\n April 24t...,Self Help
2,A Sand County Almanac and Sketches Here and There,Aldo Leopold,https://www.goodreads.com/book/show/210404.A_S...,"First published in 1949, A Sand County Almanac...",https://i.gr-assets.com/images/S/compressed.ph...,269 pages,4.28,\r\n Published\r\n 1968\r\n ...,Environment
3,The House of the Spirits,Isabel Allende,https://www.goodreads.com/book/show/9328.The_H...,In one of the most important and beloved Latin...,https://i.gr-assets.com/images/S/compressed.ph...,448 pages,4.25,\r\n Published\r\n August 30...,Historical Fiction
4,Fouché,Stefan Zweig,https://www.goodreads.com/book/show/59486.Fouch_,Joseph Fouché (1759-1820) est l'une des figure...,https://i.gr-assets.com/images/S/compressed.ph...,284 pages,4.44,\r\n Published\r\n February ...,Cultural
...,...,...,...,...,...,...,...,...,...
106,A Hippo Love Story,Karen Paolillo,https://www.goodreads.com/book/show/22736012-a...,When the threads that hold human society toget...,https://i.gr-assets.com/images/S/compressed.ph...,247 pages,4.22,\r\n Published\r\n May 2nd 2...,Africa
107,George Whitefield: God's Anointed Servant in t...,Arnold A. Dallimore,https://www.goodreads.com/book/show/29928672-g...,"This fast-paced, inspirational narrative revea...",https://i.gr-assets.com/images/S/compressed.ph...,6 pages,4.27,\r\n Published\r\n February ...,Church
108,Flying Free: My Victory over Fear to Become th...,Cecilia Aragon,https://www.goodreads.com/book/show/51577277-f...,The daughter of a Chilean father and a Filipin...,https://i.gr-assets.com/images/S/compressed.ph...,300 pages,4.62,\r\n Published\r\n September...,Aviation
109,"Sigh, Gone: A Misfit's Memoir of Great Books, ...",Phuc Tran,https://www.goodreads.com/book/show/45046838-s...,For anyone who has ever felt like they don't b...,https://i.gr-assets.com/images/S/compressed.ph...,320 pages,4.29,\r\n Published\r\n April 21s...,Biography
110,The Year of Living Danishly: My Twelve Months ...,Helen Russell,https://www.goodreads.com/book/show/27737759-t...,Denmark is officially the happiest nation on E...,https://i.gr-assets.com/images/S/compressed.ph...,10 pages,3.97,\r\n Published\r\n June 15th...,Memoir

In [18]:
data1['genres'].value_counts()

Biography               15
Memoir                  13
Autobiography            9
Nonfiction               6
Cultural                 6
History                  5
Health                   4
Travel                   3
World War II             3
Environment              3
Self Help                2
American History         2
Africa                   2
War                      2
Art                      2
Politics                 2
Romance                  2
Economics                2
Christian                1
Psychology               1
Writing                  1
Crime                    1
Childrens                1
Aviation                 1
Sports                   1
Fiction                  1
Fantasy                  1
Time Travel              1
Nature                   1
Suspense                 1
Russia                   1
Turkish                  1
Humor                    1
Historical Fiction       1
Islam                    1
Mystery                  1
Church                   1
German Literature        1
Business                 1
Magic                    1
North American Hi...     1
Military History         1
Science                  1
Womens Fiction           1
Presidents               1
Novels                   1
Name: genres, dtype: int64

## Poetry

In [19]:
number_of_pages = list(range(1,7))
all_books = []

for number in number_of_pages:
    page = requests.get(f'https://www.goodreads.com/list/show/36.Best_Poetry_Books?page={number}')
    soup = BeautifulSoup(page.content, 'html.parser')
    table = soup.find('table', attrs={'class': 'tableList js-dataTooltip'})
    table_body = table.find_all('tr')

    for entry in table_body:
        try:
            hrefs = entry.find_all(href=True)

            #get the book title
            title = hrefs[0]['title']

            #get the book author
            author = hrefs[2].get_text()

            #get the book link
            baseurl = 'https://www.goodreads.com'
            link1 = baseurl + hrefs[0]['href']
            link = hrefs[0]['href']

            #get the description of the book through its link
            page2 = requests.get(f'https://www.goodreads.com{link}')
            soup2 = BeautifulSoup(page2.content, 'html.parser')

            #select the description box
            description_box = soup2.find_all('div', attrs={'id': 'description'})

            #get the summary of each book
            book_text = description_box[0].find_all('span')[1].get_text()

            #book pictures
            image_box = soup2.find_all('img', attrs={'id' : 'coverImage'})
            picture = image_box[0]['src']

            #number of pages
            page_box = soup2.find_all('span', attrs={'itemprop':'numberOfPages'})
            page_count = page_box[0].get_text()
            
            #number of ratings
            rate_box = soup2.find_all('span', attrs={'itemprop':'ratingValue'})
            rate_count = rate_box[0].get_text()
            
            #publications
            public_box = soup2.find_all('div', attrs={'class':'row'})
            public_count = public_box[1].get_text()

            #genres
            genre_box = soup2.find_all('a', attrs={'class':'actionLinkLite bookPageGenreLink'})
            genre_list = []
            for genre in genre_box:
                genre_list.append(genre.get_text())

            #add to dictionary
            row_profile = {'name':title, 'author':author, 'link':link1, 'text':book_text,'picture':picture,
                            'page number':page_count,'rating':rate_count,'publications':public_count,'genres':genre_list[0]}

            all_books.append(row_profile)

            print(title)
        except:
            pass
    print(f'page {number} is done!')
    
f = open("books_poetry.csv", "w",encoding="utf-8")
writer = csv.DictWriter(f, fieldnames=['name', 'author', 'link', 'text', 'picture',
                                       'page number', 'rating','publications', 'genres'])
writer.writeheader()
writer.writerows(all_books)
f.close()

Ariel
The Waste Land and Other Poems
Shakespeare's Sonnets
The Raven and Other Poems
Duino Elegies
Paradise Lost
The Poetry of Robert Frost
The Selected Poetry of Rainer Maria Rilke
The Divine Comedy
The Collected Poems
100 Selected Poems
Four Quartets
The Prophet
The Essential Rumi
The Rime of the Ancient Mariner
Illuminations
The Canterbury Tales
The Collected Poems
The Complete Poems
Beowulf
The Complete English Poems
The Waste Land
100 Love Sonnets
Lunch Poems
Collected Poems, Prose, and Plays
Crush
Song of Myself
The Cantos
Metamorphoses
The Complete Poems 1927-1979
The Iliad
The Complete Poetry and Prose
Selected Poems
The Odyssey
Old Possum's Book of Practical Cats
Selected Poems and Fragments
The Portable Dorothy Parker
A World of Verse
The Collected Poems, Vol. 1: 1909-1939
Selected Poems
The Aeneid
Collected Poems
Autumn Sonata: Selected Poems
Collected Poems
The Iliad/The Odyssey
A Coney Island of the Mind: Poems
Rilke's Book of Hours: Love Poems to God
If Not, Winter: Fragments of Sappho
The Complete Collected Poems
Complete Works
The Dream Songs
Poems of Schiller
The Major Works
C. P. Cavafy: Collected Poems
The Selected Poems
Sir Gawain and the Green Knight
Hymns to the Night
The Fact of a Doorframe: Poems Selected and New, 1950-1984
The Complete Stories and Poems
Diving Into the Wreck
Selected Poems
The Complete Poems
Poems of Paul Celan
Paterson
The Colossus and Other Poems
The Last Gold of Expired Stars: Complete Poems 1908 - 1914
Collected Sonnets
A Book of Luminous Things: An International Anthology of Poetry
Early Writings
The Lady of Shalott
page 1 is done!
Collected Poems
Shelley's Poetry and Prose
95 Poems
Capital of Pain
Stranger Music: Selected Poems and Songs
Love Is a Dog from Hell
The Merchant of Venice
The Complete Poems of D.H. Lawrence
Faust
The Book of Love: Poems of Ecstasy and Longing
Milk and Honey
The Selected Poems, 1968-1995
Autobiography of Red
The Complete Poems
رباعيات خيام
A Child's Garden of Verses
Odes to Common Things
The Poems of Georg Trakl
White Knuckle
Poet in New York
Crow: From the Life and Songs of the Crow
A Light in the Attic
One Hundred and One Poems by Paul Verlaine: A Bilingual Edition
Inferno
A Conceptual Circus
New and Collected Poems: 1931-2001
Sappho
A Child's Christmas in Wales & Five Poems
With the people from the bridge
The Ipswich Bus
A Shropshire Lad
The Raven
The Giving Tree
The Sun and Her Flowers
The Dream of a Common Language
Thirst
They Won't Shut Up
The Captain's Verses
Finding Hope in the Darkness of Grief: Spiritual Insights Expressed Through Art, Poetry and Prose
The Complete Poems
Paris Spleen
Heal With Me & Our Journey Goes On
Spoon River Anthology
The Wild Iris
The Epic of Gilgamesh
The Bridge
Selected Poems
Collected Poems of Sara Teasdale
Sailing Alone Around the Room: New and Selected Poems
Eating Fire: Selected Poetry 1965-1995
Blood Sugar
Don Juan
Why I Wake Early
She Said!: The Book of Quotes
New and Selected Poems, 1974-1994
Honest
The Unwords
Complete Poems
The Song of Roland
Lyrical Ballads
Night Poems
Morning in the Burned House
The Man Suit
The Collected Poems of Frank O'Hara
Delights and Shadows
Without End: New and Selected Poems
The Creep
The Half-Finished Heaven
The Selected Poetry
Nine Horses
The Collected Poems of Audre Lorde
Rain and Embers
page 2 is done!
Still Another Day
Three Poems
Walking to Martha's Vineyard
The Bedbug and Selected Poetry
Glass, Irony and God
The Battlefield Where the Moon Says I Love You
Selected Poems
The Sound of Water: Haiku by Basho, Buson, Issa, and Other Poets
A Tear and a Smile
The World's Wife
The American Night: The Lost Writings, Vol. 2
Collected Poems, 1947-1980
The Narrow Road to the Deep North and Other Travel Sketches
Finding Identity
Cottonmouth Kisses
The Pustoy
Eating Salad Drunk: Haikus for the Burnout Age by Comedy Greats
Complete Poems
Annabel Lee
The Way Things Are
The Axion Esti
Eugene Onegin
The Black Unicorn: Poems
Love & Misadventure
Final Harvest: Emily Dickinson's Poems
The Princess Saves Herself in This One
Falling Up
The Golden Gate
The Collected Poems, 1956-1998
Civil War Poetry and Prose
On the Bus With Rosa Parks
T.S. Eliot Reads: The Wasteland, Four Quartets and Other Poems
Turtle Island
Averno
Book of Longing
An Old Man
An Inkling Hope: Select Poems
More To Life
Anatomy of a Poet
Gasoline & The Vestal Lady on Brattle
Love Poems of Elizabeth and Robert Browning
Prayers Poems Songs
Le Monogramme
We Walk Alone
The Road Not Taken and Other Poems
Words Under the Words: Selected Poems
Work of a Common Woman: The Collected Poetry of Judy Grahn 1964-1977
Crossing the Water
Caresses Soft as Sandpaper
Ariel: The Restored Edition
Wilderness: The Lost Writings, Vol. 1
Poems, 1965-1975
Midwinter Day
Tender Buttons
Cracked - Timeless Topics of Nature, Courage and Endurance
Otherwise: New and Selected Poems
The Promises of Glass: Poems
The Dream of the Unified Field: Selected Poems, 1974-1994
Renascence and Other Poems
Citizen: An American Lyric
Poems and Fragments
Satan Says
Selected Poems
The Trouble With Poetry - And Other Poems
Unopened
Кобзар
Leaf
page 3 is done!
The Temple: The Poetry of George Herbert
Midnight Poems
Selected Poems
Felt: Poems
Alone with Other People
The Sonnets
Icarus and Other Poems
Lighthead
The Dance Most of All: Poems
What Is This Thing Called Love: Poems
Corpse Delectable
Full Force
The Book of Frank
Ποίηση
Listen!
The Casting of Bells
Frost: Poems
And Still I Rise
War Music: An Account of Books 1-4 and 16-19 of Homer's Iliad
How the Grinch Stole Christmas!
The Poet's Companion: A Guide to the Pleasures of Writing Poetry
Poems Seven: New and Complete Poetry
The Song of Hiawatha
Gitanjali
The Lady of the Lake
Tao Te Ching: A New English Version
What the Living Do: Poems
“A”
The Wellspring
Night Sky with Exit Wounds
A Season in Hell and The Drunken Boat
Elegy
Play the Piano Drunk Like a Percussion Instrument Until the Fingers Begin to Bleed a Bit
Selected Odes
A Thousand Mornings
Selected Poems
Henry Wadsworth Longfellow: Poems and Other Writings
Caressed by an Elfin Breeze: The Poems of Zardoa Silverstar
Poems and Prose
The Night Before Christmas
Kings of the Fucking Sea
In the Eyes of a Military Wife
Where Pain Thrives
A Season of Shooting Stars
The Merchant of Stories: A Creative Entrepreneur's Journey
On the Blue Shore of Silence: Poemas frente al mar
I Liked You When I Thought I was Dead
The Portable Beat Reader
The Tent
Lord Byron: The Major Works
Dover Beach and Other Poems
Evangeline: A Tale of Acadie
The Rhapsody of the Ant Woman: Poem with Complementary Drawings
One with Others: [a little book of her days]
Faithful and Virtuous Night
Teaching My Mother How to Give Birth
Refusing Heaven
The New American Poetry, 1945-1960
Donkey Gospel
Hasretinden Prangalar Eskittim
Ill Lit: Selected  New Poems
All of Us: the Collected Poems
The Highwayman
The Collected Poems of Alberto Caeiro
The Leaf and the Cloud: A Poem
The Lusiads
Selected Poems
The Dream Police: Selected Poems, 1969-1993
alphabet
Anxiety
Carry On Dancing
Hot Water Bottle Hill
page 4 is done!
Lessness and More
Loose Woman
Cuttlefish Bones
Blackbird and Wolf: Poems
No Matter the Wreckage
The Cat in the Hat
The Remaining Difficulty
A Deep and Gorgeous Thirst
Uncollected Poems
The Love Poems of Rumi
Ben Sana Mecburum
The Odes
Selected Poems
Spring Essence: The Poetry of Hô Xuân Huong
Nothing Left to Lose
Almond Blossoms and Beyond
Poems: The Weight of Oranges, Miner's Pond, Skin Divers
Now We Are Six
bone
The Oresteia
The Whitsun Weddings
My Last Duchess and Other Poems
Winter's Homecoming and Other Poems
Byron's Poetry
Orlando Furioso
Winter Garden
View with a Grain of Sand: Selected Poems
Selected Poetry of William Wordsworth
The Other Side of Ourselves
What Narcissism Means to Me
Rainy Day Poems
Children of Paradise
Idylls of the King
Επιτάφιος
Scary, No Scary
Five T'ang Poets
The Marriage of Heaven and Hell
The Poet X
The Beatles Illustrated Lyrics
The Babies
Nature: Poems Old and New
Shy Green Fields
The Beauty of the Husband: A Fictional Essay in 29 Tangos
Belonging: New Poetry by Iranians Around the World
Millay
E.E. Cummings: Complete Poems 1904-1962
Stag's Leap: Poems
The Maximus Poems
The Brother Swimming Beneath Me

The Moon Is Always Female: Poems
Poems
Winter Sky: New and Selected Poems, 1968-2008
Facts About the Moon
White Elephant
A Night Without Armor: Poems
New Selected Poems
Love and Other Collisions
She
Goblin Market
Basho: The Complete Haiku
The Book of Disquiet: The Complete Edition
The Voice at 3:00 A.M.: Selected Late and New Poems
Paradise Lost and Paradise Regained
Dreaming My Animal Selves/Le Songe de Mes Ames Animales
Love Will Burst into a Thousand Shapes
page 5 is done!
Out of Danger
The Feeling May Remain
Goblin Market and Other Poems
Dystopia and Derelict Dreams: Poems
Poems from a Runaway
Poems of Love and Letting Go
Lost and Found
The Charnel Rose, Senlin: a Biography, and Other Poems
Between The Lines: Volumes of Words Unspoken
From the Mundane to the Magical
Sevda Sözleri
Les Contemplations
Actual Air
A World of Terror
Cantos de Maldoror
The Tale of Kiều
Belly of the Beast
New Beat Newbie
Book One: Sporadic Memories
The Little Light
Treason
Good Poems for Hard Times
The Complete Poems
Wszystkie wiersze
An Elven Game of Rhymes: Book Two of the Magical Poems of Zardoa Silverstar
Espantapájaros
Abandoned Breaths
What About This: Collected Poems of Frank Stanford
Selected Poems
Selected Poems
I Have to Go Back to 1994 and Kill a Girl: Poems
Love Poems
Ham on Rye
Li Po and Tu Fu: Poems
Τα ποίηματα Α΄: 1897-1918
Poems Retrieved
The Tale of Peter Rabbit
Sunstone/Piedra De Sol
Rapture
Book Too: Because of Grandmother
Rooms for Rent in the Outer Planets: Selected Poems 1962-1996
Bütün Şiirleri
Loba
Disenchanted and Disgruntled
Collected Poems and Letters from America with Photographs and a new Introduction
Art of 4 Elements
Selected Writings
Lilies Without
Empty Shoes: Poems on the Hungry and the Homeless
A Village Life
The Complete Poems
Language for a New Century: Contemporary Poetry from the Middle East, Asia, and Beyond
The Complete Poems of Henry Wadsworth Longfellow
Extravagaria
The Works of Elizabeth Barrett Browning
Love Songs
The Great Enigma: New Collected Poems
Collected Poems: 1945-1990
Poisoned Apples: Poems for You, My Pretty
page 6 is done!

In [20]:
data2 = pd.read_csv("books_poetry.csv")
data2

,name,author,link,text,picture,page number,rating,publications,genres
0,Ariel,Sylvia Plath,https://www.goodreads.com/book/show/395090.Ariel,Sylvia Plath's celebrated collection.When Sylv...,https://i.gr-assets.com/images/S/compressed.ph...,105 pages,4.20,\r\n Published\r\n March 6th...,Poetry
1,The Waste Land and Other Poems,T.S. Eliot,https://www.goodreads.com/book/show/400412.The...,Few readers need any introduction to the work ...,https://i.gr-assets.com/images/S/compressed.ph...,88 pages,4.21,\r\n Published\r\n August 4t...,Poetry
2,Shakespeare's Sonnets,William Shakespeare,https://www.goodreads.com/book/show/42038.Shak...,The Arden Shakespeare has long been acclaimed ...,https://i.gr-assets.com/images/S/compressed.ph...,488 pages,4.24,\r\n Published\r\n August 21...,Poetry
3,The Raven and Other Poems,Edgar Allan Poe,https://www.goodreads.com/book/show/269322.The...,"A chilling, thrilling collection of Edgar Alla...",https://i.gr-assets.com/images/S/compressed.ph...,73 pages,4.30,\r\n Published\r\n September...,Poetry
4,Duino Elegies,Rainer Maria Rilke,https://www.goodreads.com/book/show/53111.Duin...,"We have a marvelous, almost legendary image of...",https://i.gr-assets.com/images/S/compressed.ph...,204 pages,4.43,\r\n Published\r\n June 17th...,Poetry
...,...,...,...,...,...,...,...,...,...
400,The Works of Elizabeth Barrett Browning,Elizabeth Barrett Browning,https://www.goodreads.com/book/show/2090229.Th...,This collection was designed for optimal navig...,https://i.gr-assets.com/images/S/compressed.ph...,624 pages,4.23,\r\n Published\r\n January 1...,Poetry
401,Love Songs,Sara Teasdale,https://www.goodreads.com/book/show/1294049.Lo...,Teasdale's work has always been characterized ...,https://i.gr-assets.com/images/S/compressed.ph...,83 pages,4.08,\r\n Published\r\n 2009\r\n ...,Poetry
402,The Great Enigma: New Collected Poems,Tomas Tranströmer,https://www.goodreads.com/book/show/305941.The...,The Collected Poems of one of the world's grea...,https://i.gr-assets.com/images/S/compressed.ph...,288 pages,4.28,\r\n Published\r\n October 1...,Poetry
403,Collected Poems: 1945-1990,R.S. Thomas,https://www.goodreads.com/book/show/1988291.Co...,"A collection of R.S. Thomas's poems, published...",https://i.gr-assets.com/images/S/compressed.ph...,560 pages,4.41,\r\n Published\r\n October 5...,Poetry
404,"Poisoned Apples: Poems for You, My Pretty",Christine Heppermann,https://www.goodreads.com/book/show/20483085-p...,"Once upon a time...you were a princess,or an o...",https://i.gr-assets.com/images/S/compressed.ph...,107 pages,3.56,\r\n Published\r\n September...,Poetry

In [21]:
data2['genres'].value_counts()

Poetry           367
Classics          19
Childrens          4
Fiction            4
Adult              2
Spirituality       2
Philosophy         2
Horror             1
Music              1
Holiday            1
Short Stories      1
Contemporary       1
Name: genres, dtype: int64

In [17]:
genre_list

['Poetry',
 'Feminism',
 'LGBT',
 'Queer',
 'LGBT',
 'Classics',
 'Womens',
 'Literature',
 'American',
 'Fiction',
 'Female Authors',
 'Literature']